"""
report_generator.py  --  Deterministic (rule) Markdown report generator.

This is the **fallback** path for the three deliverable documents. When a
language model is configured the documents are written by
``core/report_llm.py``; when it is absent or a call fails, the
orchestrator (``core/report_pipeline.py``) falls back here so generation
always completes offline.

Both paths emit the *same IEEE 829 section structure*, so a reader cannot
tell design-time which engine produced a given document beyond the
provenance banner and the tool-measured generation-metrics block. Every
table, count and classification is filled from the current run's data;
nothing is invented. Inputs are accepted as pandas DataFrames or plain
lists of dicts, and every field access is defensive.

The hand-authored documents under the repository ``docs/`` directory
remain the gold reference; files produced here live under
``outputs/run_<ts>/docs/``.
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import Any, Dict, List, Optional, Sequence

# Default identity of the target application. Overridable through ``meta``.
DEFAULT_TARGET_APP = "Mini-E-Commerce Backend (Django REST)"

# Replaced post-generation by the orchestrator with the tool-measured
# document-generation time + token usage (see core/report_pipeline.py).
# Both the LLM prompts and this rule generator emit it verbatim, so the
# same injection works regardless of which engine produced the document.
METRICS_MARKER = "<!-- AUTOTESTDESIGN_METRICS -->"

# Canonical coverage-type → (technique, box) mapping used across reports.
_TYPE_TECHNIQUE = {
    "positive": ("Equivalence Partitioning", "black-box"),
    "negative": ("Equivalence Partitioning", "black-box"),
    "boundary": ("Boundary Value Analysis", "black-box"),
    "combination": ("Decision Table Testing", "black-box"),
}
_WHITE_BOX_TECHNIQUE = "State Transition Testing"


# ---------------------------------------------------------------------------
# Input coercion & small helpers
# ---------------------------------------------------------------------------

def _run_results(run_summary: Any) -> List[Any]:
    """Extract the per-case result list from a ``RunSummary`` object or an
    equivalent dict, leaving each element in its native form (the
    elements are ``TestResult`` dataclasses, not dicts)."""
    if run_summary is None:
        return []
    results = getattr(run_summary, "results", None)
    if results is None and isinstance(run_summary, dict):
        results = run_summary.get("results")
    return list(results or [])


def _records(data: Any) -> List[Dict[str, Any]]:
    """Coerce a DataFrame / list-of-dicts / None into a list of dicts."""
    if data is None:
        return []
    to_dict = getattr(data, "to_dict", None)
    if callable(to_dict) and hasattr(data, "columns"):  # pandas DataFrame
        return data.to_dict(orient="records")
    if isinstance(data, list):
        return [r for r in data if isinstance(r, dict)]
    if isinstance(data, dict):
        for key in ("test_cases", "optimized_test_cases", "coverages"):
            inner = data.get(key)
            if isinstance(inner, list):
                return [r for r in inner if isinstance(r, dict)]
    return []


def _md_table(headers: Sequence[str], rows: Sequence[Sequence[Any]],
              *, aligns: Optional[Sequence[str]] = None,
              empty: str = "_No data for this run._") -> str:
    """Render a GitHub-flavoured Markdown table. ``aligns`` entries are
    'l' | 'c' | 'r'; defaults to left."""
    if not rows:
        return empty
    sep_map = {"l": "---", "c": ":---:", "r": "---:"}
    seps = [sep_map.get((aligns or [])[i] if aligns and i < len(aligns)
                        else "l", "---") for i in range(len(headers))]

    def _cell(v: Any) -> str:
        return str(v).replace("\n", " ").replace("|", "\\|")

    lines = ["| " + " | ".join(_cell(h) for h in headers) + " |",
             "| " + " | ".join(seps) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(_cell(c) for c in row) + " |")
    return "\n".join(lines)


def _provenance(meta: Dict[str, Any], doc_title: str) -> str:
    """Standard provenance banner placed at the top of every report."""
    run_id = meta.get("run_id", "run_<unknown>")
    when = meta.get("generated_at") or datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S")
    target = meta.get("target_app", DEFAULT_TARGET_APP)
    engine = meta.get("engine_source", "rule pipeline")
    return (
        f"# {doc_title}\n\n"
        f"> _Auto-generated by **AutoTestDesign** (rule engine) for run "
        f"`{run_id}` on {when}._\n"
        f"> _Target application: **{target}**. Design engine: {engine}._\n")


def _norm_level(value: Any) -> str:
    s = str(value or "").strip().lower()
    if s.startswith("high"):
        return "High"
    if s.startswith("med"):
        return "Medium"
    if s.startswith("low"):
        return "Low"
    return str(value or "—")


def _score(rec: Dict[str, Any]) -> float:
    try:
        return float(rec.get("risk_score", 0) or 0)
    except (TypeError, ValueError):
        return 0.0


def _feature_of(rec: Dict[str, Any]) -> str:
    """Best available short description of a requirement."""
    for key in ("feature", "raw_requirement", "expected_action",
                "target_module"):
        val = rec.get(key)
        if val:
            text = str(val).strip()
            return text[:70] + ("…" if len(text) > 70 else "")
    return "—"


def _timings_table(pipeline_timings: Optional[List[Dict[str, Any]]]) -> str:
    """Render the tool-measured design-phase pipeline timings."""
    rows = [[t.get("stage", "—"), t.get("engine", "—"),
             round(float(t.get("seconds", 0) or 0), 3)]
            for t in (pipeline_timings or [])]
    if not rows:
        return "_No pipeline timings were recorded for this run._"
    total = round(sum(r[2] for r in rows), 3)
    rows.append(["**Total**", "", total])
    return _md_table(["Stage", "Engine", "Seconds"], rows,
                     aligns=["l", "l", "r"])


# ---------------------------------------------------------------------------
# 1. Risk Analysis Report  (IEEE 829-style numbered sections)
# ---------------------------------------------------------------------------

def generate_risk_analysis_report(requirements: Any, risk: Any,
                                  meta: Dict[str, Any]) -> str:
    reqs = _records(requirements)
    risks = _records(risk)
    feature_by_req = {r.get("requirement_id"): _feature_of(r) for r in reqs}
    target = meta.get("target_app", DEFAULT_TARGET_APP)

    register = sorted(risks, key=_score, reverse=True)
    counts = {"High": 0, "Medium": 0, "Low": 0}
    by_level: Dict[str, List[str]] = {"High": [], "Medium": [], "Low": []}
    for r in risks:
        lvl = _norm_level(r.get("risk_level") or r.get("priority"))
        if lvl in counts:
            counts[lvl] += 1
            by_level[lvl].append(str(r.get("requirement_id", "?")))

    out: List[str] = [_provenance(meta, f"Risk Analysis Report — {target}")]

    out.append(
        f"\n## 1. Report identifier\n\n"
        f"Risk Analysis Report for run `{meta.get('run_id', '?')}`, "
        f"concerning the **target application** ({target}) — not the "
        "AutoTestDesign tool.")

    out.append(
        "\n## 2. Introduction\n\n"
        f"This report rates the **{len(risks)}** catalogued requirements of "
        "the target application by product risk so that test effort can be "
        "concentrated where a defect is both likely and damaging "
        "(ISTQB 2018; ISO/IEC/IEEE 29119-1). The risk level of each "
        "requirement governs its coverage depth downstream.")

    out.append(
        "\n## 3. Risk assessment method\n\n"
        "Each requirement is rated 1–3 on four dimensions — "
        "`business_impact`, `failure_probability`, `complexity`, "
        "`failure_impact`. The four ratings (sum 4–12) are linearly "
        "rescaled to a 1–10 `risk_score`, mapped to a level: 1–3 Low, "
        "4–7 Medium, 8–10 High.")

    reg_rows = [
        [r.get("requirement_id", "?"),
         feature_by_req.get(r.get("requirement_id"), "—"),
         _norm_level(r.get("risk_level") or r.get("priority")),
         r.get("risk_score", "—")]
        for r in register]
    out.append(
        "\n## 4. Risk register\n\n"
        "**Table 1.** Requirements ordered by descending risk score.\n\n"
        + _md_table(["Requirement", "Feature", "Level", "Score"], reg_rows,
                    aligns=["l", "l", "l", "r"]))

    dist_rows = [[lvl, counts[lvl], ", ".join(by_level[lvl]) or "—"]
                 for lvl in ("High", "Medium", "Low")]
    out.append(
        "\n## 5. Risk distribution\n\n"
        "**Table 2.** Count of requirements per risk level.\n\n"
        + _md_table(["Level", "Count", "Requirements"], dist_rows,
                    aligns=["l", "r", "l"])
        + "\n\n```mermaid\npie showData\n    title Risk level distribution\n"
        + f"    \"High\" : {counts['High']}\n"
        + f"    \"Medium\" : {counts['Medium']}\n"
        + f"    \"Low\" : {counts['Low']}\n```")

    out.append("\n## 6. High-risk items\n")
    highs = [r for r in register
             if _norm_level(r.get("risk_level") or r.get("priority")) == "High"]
    if not highs:
        out.append("\n_No requirement reached the High band in this run._")
    else:
        for r in highs:
            rid = r.get("requirement_id", "?")
            out.append(
                f"\n### 6.{highs.index(r) + 1} {rid} — "
                f"{feature_by_req.get(rid, '')} (score {r.get('risk_score', '—')})\n\n"
                f"- Dimensions — business_impact {r.get('business_impact', '—')}, "
                f"failure_probability {r.get('failure_probability', '—')}, "
                f"complexity {r.get('complexity', '—')}, "
                f"failure_impact {r.get('failure_impact', '—')}.")
            if r.get("risk_reason"):
                out.append(f"- Rationale — {r.get('risk_reason')}")
            out.append(
                "- Test focus — favour boundary, negative and "
                "decision-table cases on this requirement.")

    out.append(
        "\n## 7. Risk-to-coverage strategy\n\n"
        "**High** retains every generated case and favours boundary, "
        "negative and decision-table cases; **Medium** keeps one "
        "representative per coverage type plus all decision-table cases; "
        "**Low** deduplicates by coverage type, always keeping at least "
        "one case. The deepest coverage therefore falls on the High-risk "
        "items above.")

    out.append(
        "\n## 8. Mitigation recommendations\n\n"
        + _md_table(
            ["Area", "Recommendation"],
            [[feature_by_req.get(r.get("requirement_id"),
                                 r.get("requirement_id", "?")),
              "Prioritise deep coverage; review the guard/transaction "
              "logic that drives its High rating."]
             for r in highs] or [["—", "No High-risk areas in this run."]]))

    out.append(
        "\n## 9. Limitations and approvals\n\n"
        "The ratings are model-derived judgements, made reproducible by a "
        "fixed combination rule and overridable by the tester before the "
        "suite is designed.\n")

    out.append(
        "\n## References\n\n"
        "- ISO/IEC/IEEE 29119-1:2022, *Software testing — Part 1*.\n"
        "- IEEE 829-2008, *Standard for Software and System Test "
        "Documentation*.\n"
        "- ISTQB, *Foundation Level Syllabus*, 2018.\n")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# 2. Test Plan  (IEEE 829-2008 Test Plan template)
# ---------------------------------------------------------------------------

def _module_index(reqs: List[Dict[str, Any]]) -> Dict[str, List[str]]:
    index: Dict[str, List[str]] = {}
    for r in reqs:
        mod = str(r.get("target_module") or "General")
        index.setdefault(mod, []).append(str(r.get("requirement_id", "?")))
    return index


def _techniques_for_reqs(cases: List[Dict[str, Any]],
                         req_ids: Sequence[str]) -> List[str]:
    wanted = set(req_ids)
    techs: List[str] = []
    for c in cases:
        if str(c.get("requirement_id", "")) in wanted:
            tech = str(c.get("test_design_technique", "")).strip()
            if tech and tech not in techs:
                techs.append(tech)
    return techs


def generate_test_plan(requirements: Any, risk: Any, coverage: Any,
                       test_cases: Any, test_summary: Optional[Dict[str, Any]],
                       optimization_summary: Optional[Dict[str, Any]],
                       runs: Optional[List[Dict[str, Any]]],
                       meta: Dict[str, Any],
                       pipeline_timings: Optional[List[Dict[str, Any]]] = None
                       ) -> str:
    reqs = _records(requirements)
    risks = _records(risk)
    cov = _records(coverage)
    cases = _records(test_cases)
    target = meta.get("target_app", DEFAULT_TARGET_APP)

    level_by_req = {
        r.get("requirement_id"): _norm_level(
            r.get("risk_level") or r.get("priority")) for r in risks}
    modules = _module_index(reqs)
    n_cases = (test_summary or {}).get("total", len(cases))

    out: List[str] = [_provenance(meta, f"Test Plan — {target}")]

    out.append(
        f"\n## 1. Test plan identifier\n\n"
        f"Master Test Plan for run `{meta.get('run_id', '?')}`, covering "
        f"the **target application** ({target}).")

    out.append(
        "\n## 2. Introduction\n\n"
        f"This plan governs verification of the target application using "
        f"AutoTestDesign, which structured **{len(reqs)}** requirements, "
        f"derived **{len(cov)}** coverage items and generated "
        f"**{n_cases}** test cases. Objectives: verify the requirements "
        "against the running system; concentrate effort on higher-risk "
        "requirements (see the Risk Analysis Report); execute the "
        "tool-produced artefacts directly without manual transcription; "
        "and detect, repair and re-verify defects. The process has two "
        "layers — AutoTestDesign designs the artefacts, PyTest executes "
        "them.")

    item_rows = []
    for mod, ids in modules.items():
        levels = sorted({level_by_req.get(i, "—") for i in ids})
        item_rows.append([mod, ", ".join(ids), " / ".join(levels) or "—"])
    out.append(
        "\n## 3. Test items\n\n"
        "**Table 1.** Components under test.\n\n"
        + _md_table(["Component / module", "Requirements", "Risk levels"],
                    item_rows))

    out.append(
        "\n## 4. Features to be tested\n\n"
        "All catalogued functional requirements above are in scope. "
        "Non-functional attributes evaluated: **performance** (generation "
        "latency), **usability** (the guided Streamlit workflow), "
        "**security** (negative cases assert 4xx rejection), and "
        "**maintainability** (deterministic engines, unit-tested).")

    out.append(
        "\n## 5. Features not to be tested\n\n"
        "Any behaviour not covered by a catalogued requirement, plus "
        "production-scale load/stress testing and deployment, are out of "
        "scope for this plan.")

    suite_rows = []
    for mod, ids in modules.items():
        techs = _techniques_for_reqs(cases, ids) or ["—"]
        levels = sorted({level_by_req.get(i, "—") for i in ids})
        suite_rows.append([mod, ", ".join(ids), " / ".join(levels) or "—",
                           ", ".join(techs),
                           "Depth set by risk level; techniques chosen per "
                           "constraint structure."])
    out.append(
        "\n## 6. Approach (high-level test suite design)\n\n"
        "Suites are organised by component; techniques follow the "
        "ISO/IEC/IEEE 29119-4 vocabulary (EP, BVA, DT, ST), selected from "
        "risk level and constraint structure.\n\n"
        "**Table 2.** Suite-level design.\n\n"
        + _md_table(["Suite", "Requirements", "Risk level", "Techniques",
                     "Rationale"], suite_rows))

    out.append(
        "\n## 7. Item pass/fail criteria\n\n"
        "An item passes when the observed response/state matches its "
        "synthesised oracle (expected status and payload assertions); "
        "otherwise it fails and is logged for repair.")

    out.append(
        "\n## 8. Suspension and resumption criteria\n\n"
        "Execution is suspended if the backend is unreachable or the unit "
        "suite is red, and resumes once both are restored.")

    out.append(
        "\n## 9. Test deliverables\n\n"
        "Data artefacts (CSV / JSON / Excel) in `data/`, and the three "
        "Markdown reports (this plan, the risk analysis report, the "
        "detailed test design & execution) in `docs/`.")

    # 10. Tasks, schedule, cost.
    executed = bool(runs)
    out.append(
        "\n## 10. Testing tasks, schedule and cost\n\n"
        "### 10.1 Test levels and schedule\n\n"
        "**Table 3.** Test levels and objectives.\n\n"
        + _md_table(
            ["Level", "Objective", "Location"],
            [["Unit", "Verify the tool's internal engines", "`tests/unit/`"],
             ["Integration",
              "Execute tool-produced artefacts against the live backend",
              "`tests/integration/`"],
             ["System", "End-to-end backend behaviour",
              "`tests/integration/` (hand-written)"]])
        + "\n\n**Table 4.** Phase checklist.\n\n"
        + _md_table(
            ["Phase", "Activity", "Status"],
            [["Planning", "Scope, risk ranking, framework selection", "☑"],
             ["Design", "Parsing, coverage, test-case generation", "☑"],
             ["Implementation", "PyTest harness and data-driven adapter",
              "☑"],
             ["Execution", "Run all suites against the backend",
              "☑" if executed else "☐"],
             ["Reporting", "Traceability, documentation, packaging", "☐"]]))
    out.append(_cost_section(len(reqs), n_cases, optimization_summary,
                             pipeline_timings))

    out.append(
        "\n## 11. Environmental needs and chosen framework\n\n"
        "**Table 6.** Frameworks selected to execute tests on the target "
        "application.\n\n"
        + _md_table(
            ["Framework", "Used for", "Rationale"],
            [["PyTest", "Test execution",
              "Python de-facto standard; `parametrize` drives the "
              "data-driven harness; readable reports."],
             ["`requests`", "HTTP calls to the backend",
              "Simple, explicit; mirrors a real REST client."],
             ["Django REST Framework", "The system under test",
              "The framework the target application is built on."],
             ["Streamlit", "The tool's UI",
              "Interactive editable tables for human-in-the-loop review."]])
        + "\n\nSelenium and JUnit were considered and rejected: the target "
          "is a REST backend with no browser layer, so HTTP-level testing "
          "with `requests`+PyTest is more direct, and JUnit does not apply "
          "to a Python/Django stack. The backend runs locally on the URL "
          "given in the sidebar.")

    out.append(
        "\n## 12. Responsibilities and staffing\n\n"
        "**Table 7.** Roles and responsibilities.\n\n"
        + _md_table(
            ["Role", "Responsibilities"],
            [["Test lead", "Plan ownership, risk sign-off, scheduling"],
             ["Tool / pipeline",
              "Parsing, risk, coverage and test-design engines"],
             ["User interface", "Streamlit workflow, export, in-UI runner"],
             ["Target application",
              "Backend, PyTest harness, defect repair and re-test"],
             ["Documentation", "Reports, traceability, packaging"]])
        + "\n\n```mermaid\nflowchart TD\n    Lead[Test lead]\n"
          "    Lead --> Pipeline[Tool / pipeline]\n"
          "    Lead --> UI[User interface]\n"
          "    Lead --> Target[Target application]\n"
          "    Lead --> Docs[Documentation]\n```")

    high_ids = [str(r.get("requirement_id", "?")) for r in risks
                if _norm_level(r.get("risk_level") or r.get("priority"))
                == "High"]
    out.append(
        "\n## 13. Risks and contingencies\n\n"
        "Product risk is detailed in the Risk Analysis Report. The "
        f"High-risk requirements requiring the deepest coverage are: "
        f"{', '.join(high_ids) or 'none in this run'}.")

    out.append(
        "\n## References\n\n"
        "- IEEE 829-2008, *Standard for Software and System Test "
        "Documentation*.\n"
        "- ISO/IEC/IEEE 29119-4:2021, *Test techniques*.\n"
        "- ISTQB, *Foundation Level Syllabus*, 2018.\n")
    return "\n".join(out) + "\n"


def _cost_section(n_reqs: int, n_cases: int,
                  optimization_summary: Optional[Dict[str, Any]],
                  pipeline_timings: Optional[List[Dict[str, Any]]]) -> str:
    """Cost estimation: a manual-vs-tool effort estimate, the measured
    design-phase pipeline timings, and the metrics marker the orchestrator
    replaces with measured generation time + token usage."""
    manual_minutes_per_case = 20
    manual_hours = round(n_cases * manual_minutes_per_case / 60.0, 1)
    tool_review_minutes_per_req = 5
    tool_hours = round(n_reqs * tool_review_minutes_per_req / 60.0, 1)
    saved = round(manual_hours - tool_hours, 1)
    opt_note = ""
    if optimization_summary:
        opt_note = (
            f" Risk-based optimisation reduced the executable set from "
            f"{optimization_summary.get('original_count', '—')} to "
            f"{optimization_summary.get('optimized_count', '—')} cases "
            f"(strategy: {optimization_summary.get('strategy', '—')}).")
    return (
        "\n### 10.2 Cost estimation\n\n"
        f"Effort is estimated from this run's volume — **{n_reqs}** "
        f"requirements and **{n_cases}** generated test cases.\n\n"
        "**Table 5a.** Effort comparison (person-hours).\n\n"
        + _md_table(
            ["Approach", "Basis", "Estimated effort"],
            [["Manual design & scripting",
              f"{n_cases} cases × {manual_minutes_per_case} min",
              f"≈ {manual_hours} h"],
             ["AutoTestDesign (review only)",
              f"{n_reqs} req × {tool_review_minutes_per_req} min review + "
              "~0 generation", f"≈ {tool_hours} h"],
             ["Saving", "manual − tool", f"≈ {saved} h"]],
            aligns=["l", "l", "r"])
        + "\n\nThe marginal per-project design+execution cost approaches "
          "zero." + opt_note
        + "\n\n**Table 5b.** Measured design-phase pipeline timings "
          "(tool-instrumented, wall-clock).\n\n"
        + _timings_table(pipeline_timings)
        + "\n\n**Document generation metrics** (model-call time and token "
          "usage, tool-measured):\n\n" + METRICS_MARKER)


# ---------------------------------------------------------------------------
# 3. Detailed Test Design & Execution
#    (IEEE 829 Test Design Spec + Test Case Spec + Test Summary Report)
# ---------------------------------------------------------------------------

def _focus_module(reqs: List[Dict[str, Any]],
                  risks: List[Dict[str, Any]]) -> Optional[str]:
    if not reqs:
        return None
    module_by_req = {r.get("requirement_id"): str(r.get("target_module")
                                                   or "General")
                     for r in reqs}
    best_mod, best_score = None, -1.0
    high_count: Dict[str, int] = {}
    for r in risks:
        mod = module_by_req.get(r.get("requirement_id"))
        if mod is None:
            continue
        if _norm_level(r.get("risk_level") or r.get("priority")) == "High":
            high_count[mod] = high_count.get(mod, 0) + 1
        sc = _score(r)
        if sc > best_score or (sc == best_score and high_count.get(mod, 0)
                               > high_count.get(best_mod, 0)):
            best_mod, best_score = mod, sc
    return best_mod or str(reqs[0].get("target_module") or "General")


def _stringify(value: Any, limit: int = 90) -> str:
    text = str(value if not isinstance(value, (dict, list)) else value).strip()
    return text[:limit] + ("…" if len(text) > limit else "")


def generate_detailed_design(requirements: Any, risk: Any, coverage: Any,
                             test_cases: Any, run_summary: Any,
                             meta: Dict[str, Any],
                             runs: Optional[List[Dict[str, Any]]] = None) -> str:
    reqs = _records(requirements)
    risks = _records(risk)
    cov = _records(coverage)
    cases = _records(test_cases)

    module = _focus_module(reqs, risks)
    mod_req_ids = [str(r.get("requirement_id", "?")) for r in reqs
                   if str(r.get("target_module") or "General") == module]
    id_set = set(mod_req_ids)
    feature_by_req = {r.get("requirement_id"): _feature_of(r) for r in reqs}

    out: List[str] = [_provenance(
        meta, f"Detailed Test Design and Execution — {module}")]

    out.append(
        f"\n## 1. Design specification identifier\n\n"
        f"Detailed test design & execution for the **{module}** module, "
        f"run `{meta.get('run_id', '?')}`.")

    out.append(
        "\n## 2. Concept and features to be tested\n\n"
        f"The **{module}** module is the highest-risk component of the "
        "target application (see the Risk Analysis Report). Its rules "
        "co-act, justifying a combination of black-box (EP, BVA, DT) and "
        "white-box (ST) techniques.\n\n"
        "**Table 1.** Requirements served by this module.\n\n"
        + _md_table(["Requirement", "Feature"],
                    [[rid, feature_by_req.get(rid, "—")]
                     for rid in mod_req_ids]))

    mod_cov = [c for c in cov if str(c.get("requirement_id", "")) in id_set]
    out.append(
        "\n## 3. Coverage-item identification\n\n"
        "The coverage engine expands each requirement's constraints into "
        "positive / negative / boundary items.\n\n"
        "**Table 2.** Coverage items for the module.\n\n"
        + _md_table(
            ["Coverage item", "Requirement", "Type", "Strategy"],
            [[_stringify(c.get("coverage_item"), 60),
              c.get("requirement_id", "?"), c.get("coverage_type", "—"),
              c.get("coverage_strategy", "—")] for c in mod_cov]))

    out.append(
        "\n## 4. Coverage strategy and method\n\n"
        "**Table 3.** Coverage type → technique → method.\n\n"
        + _md_table(
            ["Coverage type", "Technique", "Method"],
            [["positive", "Equivalence Partitioning",
              "Submit one valid input; assert acceptance (2xx)."],
             ["negative", "Equivalence Partitioning",
              "Submit one invalid input; assert rejection (4xx)."],
             ["boundary", "Boundary Value Analysis",
              "Sample values on and around each limit."],
             ["combination", "Decision Table Testing",
              "Exercise combinations of co-acting rules."],
             ["state transition", "State Transition Testing (white-box)",
              "Traverse valid transitions and reject invalid guards."]]))

    mod_cases = [c for c in cases
                 if str(c.get("requirement_id", "")) in id_set]
    tech_counts: Dict[str, int] = {}
    box_counts = {"black-box": 0, "white-box": 0}
    case_rows = []
    for c in mod_cases:
        tech = str(c.get("test_design_technique", "—"))
        ctype = str(c.get("coverage_type", "")).lower()
        tech_counts[tech] = tech_counts.get(tech, 0) + 1
        box = ("white-box" if tech == _WHITE_BOX_TECHNIQUE
               else _TYPE_TECHNIQUE.get(ctype, ("", "black-box"))[1])
        box_counts[box] = box_counts.get(box, 0) + 1
        case_rows.append([
            c.get("test_case_id", "?"), tech, c.get("coverage_type", "—"),
            box, _stringify(c.get("description"), 60),
            _stringify(c.get("expected_result"), 50)])
    out.append(
        "\n## 5. Test case specification and coverage\n\n"
        f"The module is covered by **{len(mod_cases)}** test cases — "
        f"{box_counts.get('black-box', 0)} black-box and "
        f"{box_counts.get('white-box', 0)} white-box. Every case traces to "
        "a coverage item in §3.\n\n"
        "**Table 4.** Designed test cases for the module.\n\n"
        + _md_table(
            ["Test case", "Technique", "Coverage type", "Box", "Description",
             "Expected result"], case_rows))
    if tech_counts:
        out.append(
            "\n**Table 5.** Cases by technique.\n\n"
            + _md_table(["Technique", "Cases"],
                        [[t, n] for t, n in sorted(tech_counts.items())],
                        aligns=["l", "r"]))

    out.append(
        "\n## 6. Prompt design and traceability\n\n"
        "The chain *requirement → coverage item → test case → executing "
        "function* is fully reconstructable through each case's "
        "`traceability` block. The LLM stages (parsing, risk) are "
        "schema-constrained and run at `temperature=0`, so the structured "
        "inputs are reproducible.")

    out.append("\n## 7. Result analysis (Test Summary Report)\n")
    out.append(_modes_section(runs or []))
    out.append(_result_section(run_summary, id_set))

    out.append(
        "\n## 8. Evidence-based improvement and designer involvement\n\n"
        "Each failing case traces to one requirement and one coverage "
        "item, localising the defect class the technique exposed. The "
        "designer may revise coverage items, strategies and cases "
        "interactively in the tool; each edit invalidates downstream "
        "artefacts, which regenerate, so the suite always reflects the "
        "latest decisions.")

    out.append(
        "\n## References\n\n"
        "- IEEE 829-2008, *Standard for Software and System Test "
        "Documentation*.\n"
        "- ISO/IEC/IEEE 29119-4:2021, *Test techniques*.\n"
        "- ISTQB, *Foundation Level Syllabus*, 2018.\n")
    return "\n".join(out) + "\n"


_HTTP_MODE_LABEL = {"dedup": "representative-per-key",
                    "full": "individual (full)"}


def _modes_section(runs: List[Dict[str, Any]]) -> str:
    if not runs:
        return ""

    def _g(summary: Any, name: str, default: Any = 0) -> Any:
        return getattr(summary, name, default)

    rows = []
    for r in runs:
        s = r.get("summary")
        rows.append([
            r.get("source", "—"),
            _HTTP_MODE_LABEL.get(r.get("http_mode"), r.get("http_mode", "—")),
            r.get("generated_count", "—"), r.get("executed_count", "—"),
            _g(s, "passed"), _g(s, "failed"), _g(s, "skipped"),
            round(float(_g(s, "duration_seconds", 0.0)), 2)])
    note = ""
    if any(r.get("http_mode") == "dedup" for r in runs) and \
            any(r.get("http_mode") == "full" for r in runs):
        note = (
            "\n\nThe deduplicated and full-individual runs report the same "
            "pass/fail verdict, confirming that representative-per-key "
            "execution covers the same observable behaviour as executing "
            "every case.")
    return (
        "\n**Table 6.** Execution outcome by run mode (source × HTTP "
        "execution).\n\n"
        + _md_table(
            ["Source", "HTTP execution", "Designed", "Executed", "Passed",
             "Failed", "Skipped", "Seconds"], rows,
            aligns=["l", "l", "r", "r", "r", "r", "r", "r"]) + note)


def _result_section(run_summary: Any, id_set: set) -> str:
    results = _run_results(run_summary)
    if not results:
        return ("\n_The suite has not yet been executed for this run. Run "
                "the tests (Step 8) and regenerate this report to populate "
                "the execution results._")

    def _attr(obj: Any, name: str, default: Any = "") -> Any:
        if isinstance(obj, dict):
            return obj.get(name, default)
        return getattr(obj, name, default)

    rows, passed, failed = [], 0, 0
    for r in results:
        rid = str(_attr(r, "requirement_id"))
        if id_set and rid not in id_set:
            continue
        outcome = str(_attr(r, "outcome", "")).lower()
        if outcome == "passed":
            passed += 1
        elif outcome in ("failed", "error"):
            failed += 1
        rows.append([_attr(r, "test_case_id", "?"), rid,
                     _attr(r, "coverage_type", "—"), outcome.upper() or "—",
                     _stringify(_attr(r, "message"), 60)])
    total = getattr(run_summary, "total", None)
    duration = getattr(run_summary, "duration_seconds", None)
    header = (f"\nThe canonical run reported **{passed} passed**, "
              f"**{failed} failed** for this module")
    if total is not None:
        header += f" (suite total {total}"
        if duration is not None:
            header += f", {round(float(duration), 2)} s"
        header += ")"
    header += ".\n"
    return (header + "\n**Table 7.** Per-case execution outcome (canonical "
            "run).\n\n" + _md_table(
                ["Test case", "Requirement", "Coverage type", "Outcome",
                 "Message"], rows))


# ---------------------------------------------------------------------------
# Rule-only entry point (used directly by tests / offline scripts; the
# live orchestrator in core/report_pipeline.py calls the three generators
# individually so it can mix LLM and rule output per document).
# ---------------------------------------------------------------------------

def generate_all(requirements: Any, risk: Any, coverage: Any,
                 test_cases: Any, docs_dir: str,
                 test_summary: Optional[Dict[str, Any]] = None,
                 optimization_summary: Optional[Dict[str, Any]] = None,
                 run_summary: Any = None,
                 runs: Optional[List[Dict[str, Any]]] = None,
                 pipeline_timings: Optional[List[Dict[str, Any]]] = None,
                 meta: Optional[Dict[str, Any]] = None) -> Dict[str, str]:
    """Render all three reports with the rule engine and write them.

    Note: the ``METRICS_MARKER`` is left in place here; the orchestrator
    is responsible for replacing it. When used standalone (tests), the
    marker simply remains as an HTML comment.
    """
    os.makedirs(docs_dir, exist_ok=True)
    meta = dict(meta or {})
    meta.setdefault("generated_at",
                    datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

    documents = {
        "risk_analysis_report": (
            "risk_analysis_report.md",
            generate_risk_analysis_report(requirements, risk, meta)),
        "test_plan": (
            "test_plan.md",
            generate_test_plan(requirements, risk, coverage, test_cases,
                               test_summary, optimization_summary, runs, meta,
                               pipeline_timings)),
        "detailed_test_design_execution": (
            "detailed_test_design_execution.md",
            generate_detailed_design(requirements, risk, coverage, test_cases,
                                     run_summary, meta, runs)),
    }
    paths: Dict[str, str] = {}
    for key, (filename, content) in documents.items():
        path = os.path.join(docs_dir, filename)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        paths[key] = path
    return paths
